<?php

namespace ContainerXCidtB8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YarJWA2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YarJWA2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YarJWA2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'stains' => ['privates', '.errored..service_locator.YarJWA2.App\\Entity\\Stains', NULL, 'Cannot autowire service ".service_locator.YarJWA2": it references class "App\\Entity\\Stains" but no such service exists.'],
        ], [
            'stains' => 'App\\Entity\\Stains',
        ]);
    }
}
