<?php

namespace ContainerXCidtB8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CIULH3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._cIULH3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._cIULH3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProjectController::edit' => ['privates', '.service_locator.bU8nL9L', 'get_ServiceLocator_BU8nL9LService', true],
            'App\\Controller\\ProjectController::remove' => ['privates', '.service_locator.bU8nL9L', 'get_ServiceLocator_BU8nL9LService', true],
            'App\\Controller\\ProjectController::removeProjectStains' => ['privates', '.service_locator.bU8nL9L', 'get_ServiceLocator_BU8nL9LService', true],
            'App\\Controller\\TachesController::edit' => ['privates', '.service_locator.YarJWA2', 'get_ServiceLocator_YarJWA2Service', true],
            'App\\Controller\\TachesController::remove' => ['privates', '.service_locator.YarJWA2', 'get_ServiceLocator_YarJWA2Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ProjectController:edit' => ['privates', '.service_locator.bU8nL9L', 'get_ServiceLocator_BU8nL9LService', true],
            'App\\Controller\\ProjectController:remove' => ['privates', '.service_locator.bU8nL9L', 'get_ServiceLocator_BU8nL9LService', true],
            'App\\Controller\\ProjectController:removeProjectStains' => ['privates', '.service_locator.bU8nL9L', 'get_ServiceLocator_BU8nL9LService', true],
            'App\\Controller\\TachesController:edit' => ['privates', '.service_locator.YarJWA2', 'get_ServiceLocator_YarJWA2Service', true],
            'App\\Controller\\TachesController:remove' => ['privates', '.service_locator.YarJWA2', 'get_ServiceLocator_YarJWA2Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ProjectController::edit' => '?',
            'App\\Controller\\ProjectController::remove' => '?',
            'App\\Controller\\ProjectController::removeProjectStains' => '?',
            'App\\Controller\\TachesController::edit' => '?',
            'App\\Controller\\TachesController::remove' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ProjectController:edit' => '?',
            'App\\Controller\\ProjectController:remove' => '?',
            'App\\Controller\\ProjectController:removeProjectStains' => '?',
            'App\\Controller\\TachesController:edit' => '?',
            'App\\Controller\\TachesController:remove' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
