<?php

namespace Container8smf1SI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZMX9vXbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZMX9vXb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZMX9vXb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'project' => ['privates', '.errored..service_locator.ZMX9vXb.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.ZMX9vXb": it references class "App\\Entity\\Project" but no such service exists.'],
            'stains' => ['privates', '.errored..service_locator.ZMX9vXb.App\\Entity\\Stains', NULL, 'Cannot autowire service ".service_locator.ZMX9vXb": it references class "App\\Entity\\Stains" but no such service exists.'],
        ], [
            'project' => 'App\\Entity\\Project',
            'stains' => 'App\\Entity\\Stains',
        ]);
    }
}
