<?php

namespace Container8smf1SI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStains2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZMX9vXb.App\Entity\Stains' shared service.
     *
     * @return \App\Entity\Stains
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZMX9vXb": it references class "App\\Entity\\Stains" but no such service exists.');
    }
}
