<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'http://todo-list:9001/build/runtime.js',
                'http://todo-list:9001/build/vendors~_tmp_copy~accueil~app~appStyle~parameter~project~statement.js',
                'http://todo-list:9001/build/vendors~accueil~app~parameter~project~statement.js',
                'http://todo-list:9001/build/vendors~app.js',
                'http://todo-list:9001/build/app.js',
            ],
        ],
        'project' => [
            'js' => [
                'http://todo-list:9001/build/runtime.js',
                'http://todo-list:9001/build/vendors~_tmp_copy~accueil~app~appStyle~parameter~project~statement.js',
                'http://todo-list:9001/build/vendors~accueil~app~parameter~project~statement.js',
                'http://todo-list:9001/build/project.js',
            ],
        ],
        'accueil' => [
            'js' => [
                'http://todo-list:9001/build/runtime.js',
                'http://todo-list:9001/build/vendors~_tmp_copy~accueil~app~appStyle~parameter~project~statement.js',
                'http://todo-list:9001/build/vendors~accueil~app~parameter~project~statement.js',
                'http://todo-list:9001/build/accueil.js',
            ],
        ],
        'parameter' => [
            'js' => [
                'http://todo-list:9001/build/runtime.js',
                'http://todo-list:9001/build/vendors~_tmp_copy~accueil~app~appStyle~parameter~project~statement.js',
                'http://todo-list:9001/build/vendors~accueil~app~parameter~project~statement.js',
                'http://todo-list:9001/build/parameter.js',
            ],
        ],
        'statement' => [
            'js' => [
                'http://todo-list:9001/build/runtime.js',
                'http://todo-list:9001/build/vendors~_tmp_copy~accueil~app~appStyle~parameter~project~statement.js',
                'http://todo-list:9001/build/vendors~accueil~app~parameter~project~statement.js',
                'http://todo-list:9001/build/statement.js',
            ],
        ],
        'appStyle' => [
            'js' => [
                'http://todo-list:9001/build/runtime.js',
                'http://todo-list:9001/build/vendors~_tmp_copy~accueil~app~appStyle~parameter~project~statement.js',
            ],
            'css' => [
                'http://todo-list:9001/build/appStyle.css',
            ],
        ],
    ],
],

]];
